name: Continuous Integration

on: 
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Composer
        uses: php-actions/composer@v6
        with:
          args: --profile --ignore-platform-reqs
          php_version: '8.0'
          version: '2.x'

      - name: Install dependencies
        run: composer install --ignore-platform-reqs
      - name: Run tests
        run: composer test